### ISSUE TITLE
Error in Android Studio 3.1.2

### ISSUE THREAD

**Issue by horuscentro** [TakeoffAndroid/RecyclerViewTemplate#5]
when i start the template there is a alert dialog showing this message:

```
Merge conflict for: AndroidManifest.xml
This file must be fixed by hand. The errors encountered during the merge are:

* Missing 'package' declaration in manifest at template AndroidManifest.xml:1:1-11:12

* Validation failed, exiting


If you proceed the resulting project may not compile or not work as intended.
```

**Comment by eif-courses** [comment]
Create as fragment in your project.

**Comment by sabiou** [comment]
Hi @horuscentro to fix this issue go to your project folder and edit your AndroidManifest.xml to correct the error. The error is due by a merge conflict between the generated manifest and the existing one in your project.
