### ISSUE TITLE
How can I add dependency line like annotationProcessor ? or testImplementation ?

### ISSUE THREAD

**Issue by sabiou** [TakeoffAndroid/RecyclerViewTemplate#7]
Hello folks ! I want to add dependency like:
` implementation "android.arch.persistence.room:runtime:$room_version"
    annotationProcessor "android.arch.persistence.room:compiler:$room_version"
testImplementation "android.arch.persistence.room:testing:$room_version"`

I know for the first line it's something like: `<dependency mavenUrl="android.arch.persistence.room:runtime:1.1.1"/>` .

**Comment by ckdevrel** [comment]
@sabiou  You can check clone the project and edit the `build.gradle` template file..
